services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zoppy
    networks:
      - pgnetwork
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

networks:
  pgnetwork:
    driver: bridge